Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"
  config.vm.box_check_update = false
  config.vm.hostname = "captex-ubuntu"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "ansible-bootstrap", type: "shell", privileged: true, run: "never", inline: <<-SHELL
    set -eu
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends ansible-core
    install -d -o vagrant -g vagrant -m 0750 /opt/captex
  SHELL
  config.vm.provider "vmware_desktop" do |provider|
    provider.gui = false
    provider.vmx["memsize"] = "2048"
    provider.vmx["numvcpus"] = "2"
  end
end
