# Alembic configuration file
[alembic]
# location of migration files
sqlalchemy.url = sqlite:///./app.db
script_location = alembic

# default to using plain `python` for the "python" executable
# requires presence of python executable in the path
python_files = *.py
python_locations = 
    %(here)s/alembic/versions
    %(here)s/alembic

sqlalchemy.echo = False

[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
